### ISSUE TITLE
cmake error on eagine_add_module_tests

### ISSUE THREAD

**Issue by Twisty9656** [matus-chochlik/eagine-all#2]
```
CMake Error at submodules/eagine-core/source/modules/eagine/types/CMakeLists.txt:118 (eagine_add_module_tests):
  Unknown CMake command "eagine_add_module_tests".
```
getting this error message when trying to build and am unsure as to why. Any advice would be appreciated.

Cheers,
Tristan

**Comment by matus-chochlik** [comment]
Hi have you checked out the git submodules?

**Comment by matus-chochlik** [comment]
What is the compiler you use, at the moment only clang 17 and higher are supported.

**Comment by Twisty9656** [comment]
ah okay cheers, my CXX compiler was set to g++. All sorted now, thanks!

**Comment by matus-chochlik** [comment]
Hi, I've tried this with g++ some tome ago, but that version kept crashing constantly so I've left it unfinished. I have plan to fix the build system when there is a proper stable support for C++ modules in cmake, so that I don't have to write a lot of compiler-specific scripts.
